### ISSUE TITLE
Cant Run SuperAGI at all after installation

### ISSUE THREAD

**Issue by adp60** [TransformerOptimus/SuperAGI#1095]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I have followed the installation steps laid out but still cant get SuperAGI to run on docker desktop. I see the following error on the terminal and think it has something to do with it. Can someone guide me on what could be causing this issue and how to fix it? Thanks in advance..

PS: Not a developer, still new to this

Here is the terminal message

superagi-backend-1          |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
superagi-backend-1          | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "None" to address: Temporary failure in name resolution
superagi-backend-1          |
superagi-backend-1          | (Background on this error at: https://sqlalche.me/e/20/e3q8)
superagi-backend-1          |
superagi-backend-1          | ERROR:    Application startup failed. Exiting.

### How to replicate your Issue?

The issue occurs during installation - setting up the docker container.

### Upload Error Log Content

superagi-backend-1          | 2023-08-21 23:00:38 UTC - Super AGI - ERROR - [/app/superagi/models/db.py:46] - Unable to connect to the database:(psycopg2.OperationalError) could not translate host name "None" to address: Temporary failure in name resolution superagi-backend-1          | superagi-backend-1          | (Background on this error at: https://sqlalche.me/e/20/e3q8) superagi-backend-1          | superagi-backend-1          | INFO:     Started server process [49] superagi-backend-1          | INFO:     Waiting for application startup. superagi-backend-1          | 2023-08-21 23:00:43 UTC - Super AGI - INFO - [/app/main.py:180] - Running Startup tasks superagi-backend-1          | ERROR:    Traceback (most recent call last): superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__ superagi-backend-1          |     self._dbapi_connection = engine.raw_connection() superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection superagi-backend-1          |     return self.pool.connect() superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect superagi-backend-1          |     return _ConnectionFairy._checkout(self) superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout superagi-backend-1          |     fairy = _ConnectionRecord.checkout(pool) superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout superagi-backend-1          |     rec = pool._do_get() superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get superagi-backend-1          |     with util.safe_reraise(): superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__ superagi-backend-1          |     raise exc_value.with_traceback(exc_tb) superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get superagi-backend-1          |     return self._create_connection() superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection superagi-backend-1          |     return _ConnectionRecord(self) superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__ superagi-backend-1          |     self.__connect() superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect superagi-backend-1          |     with util.safe_reraise(): superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__ superagi-backend-1          |     raise exc_value.with_traceback(exc_tb) superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect superagi-backend-1          |     self.dbapi_connection = connection = pool._invoke_creator(self) superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 637, in connect superagi-backend-1          |     return dialect.connect(*cargs, **cparams) superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 615, in connect superagi-backend-1          |     return self.loaded_dbapi.connect(*cargs, **cparams) superagi-backend-1          |   File "/opt/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect superagi-backend-1          |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync) superagi-backend-1          | psycopg2.OperationalError: could not translate host name "None" to address: Temporary failure in name resolution

**Comment by AJacques-UDS** [comment]
Got the same problem on Pop_OS! 22.04, seems to be something about the host name of some database

```
backend_1          | 2023-08-30 01:20:17 UTC - Super AGI - ERROR - [/app/superagi/models/db.py:46] - Unable to connect to the database:(psycopg2.OperationalError) could not translate host name "None" to address: Temporary failure in name resolution
```

It looks like it is after the configuration of the `celery` container that seems at first as completed, but fails later. Also, the message `(Background on this error at: https://sqlalche.me/e/20/e3q8)` says again that the error is outside the control of the programmers - like can't connect to the server.

**Comment by centriams** [comment]
I'm having the same exact issue. Upon loading localhost:3000. the page gets stuck on "Initializing SuperAGI..."

```
    | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied
superagi-celery-1           |
superagi-celery-1           | (Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by saezbaldo** [comment]
Having the exact same issue as centriams

**Comment by jasgeo75** [comment]
Also the same issue as centriams

Docker 24.0.5
