### ISSUE TITLE
nltk modules installation issue using Docker in Windows

### ISSUE THREAD

**Issue by AdityaKulshrestha** [TransformerOptimus/SuperAGI#1348]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Tried to install superAGI using docker in windows. I got an error in nltk installation. It was not able to download and install nltk modules. 

### Upload Error Log Content

``` > [backend compile-image 7/9] RUN python -m nltk.downloader averaged_perceptron_tagger punkt: 1.657 /usr/local/lib/python3.10/runpy.py:126: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour 1.657   warn(RuntimeWarning(msg)) 22.76 [nltk_data] Error loading averaged_perceptron_tagger: <urlopen error 22.76 [nltk_data]     EOF occurred in violation of protocol (_ssl.c:1007)> 22.76 Error installing package. Retry? [n/y/e] 22.76 Traceback (most recent call last): 22.76   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main 22.76     return _run_code(code, main_globals, None, 22.76   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code 22.76     exec(code, run_globals) 22.76   File "/opt/venv/lib/python3.10/site-packages/nltk/downloader.py", line 2544, in <module> 22.76     rv = downloader.download( 22.76   File "/opt/venv/lib/python3.10/site-packages/nltk/downloader.py", line 788, in download 22.76     choice = input().strip() 22.76 EOFError: EOF when reading a line ------ failed to solve: process "/bin/sh -c python -m nltk.downloader averaged_perceptron_tagger punkt" did not complete successfully: exit code: 1```

**Comment by Therealkorris** [comment]
running on C:? I hade some issues that got resolved whenever i cloned to C:
try that
