### ISSUE TITLE
local-llm-gpu installation / setup not working

### ISSUE THREAD

**Issue by ajay-f22** [TransformerOptimus/SuperAGI#1378]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Linux

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

local-llm-gpu not working 

### How to replicate your Issue?

git clone https://github.com/TransformerOptimus/SuperAGI.git
cd SuperAGI
docker compose -f local-llm-gpu  up --build

### Upload Error Log Content

```
super__tgwui                | 2023-12-13 13:24:17 INFO:Loading the extension "openai"...
superagi-gui-1              | - wait compiling...
super__tgwui                | 2023-12-13 13:24:17 INFO:OpenAI-compatible API URL:
super__tgwui                | 
super__tgwui                | http://127.0.0.1:5000
super__tgwui                | 
super__tgwui                | 2023-12-13 13:24:17 INFO:Loading the extension "gallery"...
super__tgwui                | Traceback (most recent call last):
super__tgwui                |   File "/app/server.py", line 247, in <module>
super__tgwui                |     create_interface()
super__tgwui                |   File "/app/server.py", line 128, in create_interface
super__tgwui                |     ui_parameters.create_ui(shared.settings['preset'])  # Parameters tab
super__tgwui                |   File "/app/modules/ui_parameters.py", line 11, in create_ui
super__tgwui                |     generate_params = presets.load_preset(default_preset)
super__tgwui                |   File "/app/modules/presets.py", line 49, in load_preset
super__tgwui                |     with open(Path(f'presets/{name}.yaml'), 'r') as infile:
super__tgwui                | FileNotFoundError: [Errno 2] No such file or directory: 'presets/simple-1.yaml'
superagi-gui-1              | - event compiled client and server successfully in 1008 ms (1718 modules)
super__tgwui exited with code 1

```

**Comment by cbluth95** [comment]
Same here.

**Comment by rounak610** [comment]
docker compose -f docker-compose-gpu.yml up --build
USE THIS COMMAND TO BUILD
Multi-GPU support has been added with this pr #1391
