### ISSUE TITLE
GETTING ISSUE WITH DIGITALOCEAN DEPLOYMENT

### ISSUE THREAD

**Issue by thinkstudyai** [TransformerOptimus/SuperAGI#1407]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

[2024-02-26 11:13:44] Process SpawnProcess-1:
[2024-02-26 11:13:44] Traceback (most recent call last):
[2024-02-26 11:13:44]   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
[2024-02-26 11:13:44]     self.run()
[2024-02-26 11:13:44]   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
[2024-02-26 11:13:44]     self._target(*self._args, **self._kwargs)
[2024-02-26 11:13:44]   File "/opt/venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
[2024-02-26 11:13:44]     target(sockets=sockets)
[2024-02-26 11:13:44]   File "/opt/venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
[2024-02-26 11:13:44]     return asyncio.run(self.serve(sockets=sockets))
[2024-02-26 11:13:44]   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
[2024-02-26 11:13:44]     return loop.run_until_complete(main)
[2024-02-26 11:13:44]   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
[2024-02-26 11:13:44]   File "/opt/venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
[2024-02-26 11:13:44]     config.load()
[2024-02-26 11:13:44]   File "/opt/venv/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
[2024-02-26 11:13:44]     self.loaded_app = import_from_string(self.app)
[2024-02-26 11:13:44]   File "/opt/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
[2024-02-26 11:13:44]     module = importlib.import_module(module_str)
[2024-02-26 11:13:44]   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
[2024-02-26 11:13:44]     return _bootstrap._gcd_import(name[level:], package, level)
[2024-02-26 11:13:44]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[2024-02-26 11:13:44]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[2024-02-26 11:13:44]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[2024-02-26 11:13:44]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[2024-02-26 11:13:44]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[2024-02-26 11:13:44]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[2024-02-26 11:13:44]   File "/app/main.py", line 15, in <module>
[2024-02-26 11:13:44]     from superagi.agent.workflow_seed import IterationWorkflowSeed, AgentWorkflowSeed
[2024-02-26 11:13:44]   File "/app/superagi/agent/workflow_seed.py", line 1, in <module>
[2024-02-26 11:13:44]     from superagi.agent.agent_prompt_builder import AgentPromptBuilder
[2024-02-26 11:13:44]   File "/app/superagi/agent/agent_prompt_builder.py", line 6, in <module>
[2024-02-26 11:13:44]     from superagi.helper.token_counter import TokenCounter
[2024-02-26 11:13:44]   File "/app/superagi/helper/token_counter.py", line 7, in <module>
[2024-02-26 11:13:44]     from superagi.models.models import Models
[2024-02-26 11:13:44]   File "/app/superagi/models/models.py", line 7, in <module>
[2024-02-26 11:13:44]     from superagi.helper.encyption_helper import decrypt_data
[2024-02-26 11:13:44]   File "/app/superagi/helper/encyption_helper.py", line 11, in <module>
[2024-02-26 11:13:44]     raise Exception("Encryption key not found in config file.")
[2024-02-26 11:13:44] Exception: Encryption key not found in config file.
[]

Getting this build error. 

### How to replicate your Issue?

OneClick DigitalOcean Deployment Button

### Upload Error Log Content

gfg

**Comment by isaiah2004** [comment]
read my fix here
https://github.com/TransformerOptimus/SuperAGI/issues/1273#issuecomment-1989031378
