### ISSUE TITLE
PS E:\SuperAGI-1> python test.py Unable to connect to the database: (psycopg2.OperationalError) could not translate host  name "super__postgres" to address:

### ISSUE THREAD

**Issue by DMTarmey** [TransformerOptimus/SuperAGI#370]
(myenv) PS E:\SuperAGI-1> python test.py
Unable to connect to the database: (psycopg2.OperationalError) could not translate host 
name "super__postgres" to address: Unknown host

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3366, in 
_wrap_pool_connect
    return fn()
           ^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, 
in __exit__
    compat.raise_(
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 388, in __init__
    self.__connect()
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 690, in __connect
    with util.safe_reraise():
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, 
in __exit__
    compat.raise_(
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "super__postgres" to address: Unknown host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\SuperAGI-1\test.py", line 109, in <module>
    run_superagi_cli(agent_name=agent_name,agent_description=agent_description,agent_goals=agent_goals)
  File "E:\SuperAGI-1\test.py", line 45, in run_superagi_cli
    session.flush()  # Flush pending changes to generate the agent's ID
    ^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 3449, in 
flush
    self._flush(objects)
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 3588, in 
_flush
    with util.safe_reraise():
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, 
in __exit__
    compat.raise_(
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 3549, in 
_flush
    flush_context.execute()
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 212, 
in save_obj
    for (
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 373, 
in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1737, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 629, in connection
    return self._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 738, in _connection_for_bind
    conn = self._parent._connection_for_bind(bind, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\orm\session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3320, in 
connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3399, in 
raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3369, in 
_wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 2203, in 
_handle_dbapi_exception_noconnection
    util.raise_(
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\base.py", line 3366, in 
_wrap_pool_connect
    return fn()
           ^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, 
in __exit__
    compat.raise_(
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 388, in __init__
    self.__connect()
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 690, in __connect
    with util.safe_reraise():
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, 
in __exit__
    compat.raise_(
pat.py", line 211, in raise_
    raise exception
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\pool\base.py", line 686, in __connect 
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect      
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "super__postgres" to address: Unknown host

(Background on this error at: https://sqlalche.me/e/14/e3q8)
(myenv) PS E:\SuperAGI-1>

**Comment by neelayan7** [comment]
test.py runs the CLI flow which we don't track now as much.
Can you pull the latest changes on main and do docker-compose up --build and try again? 
Let us know if anything is wrong.

**Comment by DMTarmey** [comment]
PS E:\SuperAGI-1> & e:/SuperAGI-1/myenv/Scripts/Activate.ps1
(myenv) PS E:\SuperAGI-1> python test.py
Traceback (most recent call last):
  File "E:\SuperAGI-1\test.py", line 7, in <module>
    from superagi.worker import execute_agent
  File "E:\SuperAGI-1\superagi\worker.py", line 6, in <module>
    from superagi.jobs.agent_executor import AgentExecutor
  File "E:\SuperAGI-1\superagi\jobs\agent_executor.py", line 13, in <module>
    from superagi.agent.super_agi import SuperAgi
  File "E:\SuperAGI-1\superagi\agent\super_agi.py", line 45, in <module>
    engine = connect_db()
             ^^^^^^^^^^^^
  File "E:\SuperAGI-1\superagi\models\db.py", line 24, in connect_db    
    engine = create_engine(db_url)
             ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\util\deprecations.py", line 375, in warned   
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 518, in create_engine     
    entrypoint = u._get_entrypoint()
                 ^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\url.py", line 662, in _get_entrypoint      
    cls = registry.load(name)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\create.py", line 518, in create_engine     
    entrypoint = u._get_entrypoint()
                 ^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\engine\url.py", line 662, in _get_entrypoint      
    cls = registry.load(name)
          ^^^^^^^^^^^^^^^^^^^
  File "E:\SuperAGI-1\myenv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 343, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgresql
(myenv) PS E:\SuperAGI-1>

**Comment by DMTarmey** [comment]
fixed
