### ISSUE TITLE
invalid_api_key error_message= error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False

### ISSUE THREAD

**Issue by AgimaFR** [TransformerOptimus/SuperAGI#387]
I made a brand new installation of the latest version of SuperAGI v0.0.5
SuperAGI is running in my browser with default parameter, but it remains stuck on the step of determining the next step.
![SuperAGI 2023-06-15 16-08-37](https://github.com/TransformerOptimus/SuperAGI/assets/54644593/a64aaea1-ddcf-4578-897d-6706e9e8a4ec)

Terminal extract
```
superagi-celery-1           |  Ensure the response can be parsed by Python json.loads.
superagi-celery-1           |  
superagi-celery-1           | [2023-06-15 13:37:49,621: INFO/ForkPoolWorker-7] error_code=invalid_api_key error_message= error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
superagi-celery-1           | [2023-06-15 13:37:49,622: WARNING/ForkPoolWorker-7] Exception:
superagi-celery-1           | [2023-06-15 13:37:49,622: WARNING/ForkPoolWorker-7]  
superagi-celery-1           | [2023-06-15 13:37:49,622: WARNING/ForkPoolWorker-7] <empty message>
superagi-celery-1           | [2023-06-15 13:37:49,664: ERROR/ForkPoolWorker-7] Task execute_agent[2a80b198-accb-411d-a3af-2468174140f5] raised unexpected: KeyError('content')
superagi-celery-1           | Traceback (most recent call last):
superagi-celery-1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
superagi-celery-1           |     R = retval = fun(*args, **kwargs)
superagi-celery-1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
superagi-celery-1           |     return self.run(*args, **kwargs)
superagi-celery-1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/autoretry.py", line 54, in run
superagi-celery-1           |     ret = task.retry(exc=exc, **retry_kwargs)
superagi-celery-1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 717, in retry
superagi-celery-1           |     raise_with_context(exc)
superagi-celery-1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/autoretry.py", line 34, in run
superagi-celery-1           |     return task._orig_run(*args, **kwargs)
superagi-celery-1           |   File "/app/superagi/worker.py", line 18, in execute_agent
superagi-celery-1           |     AgentExecutor().execute_next_action(agent_execution_id=agent_execution_id)
superagi-celery-1           |   File "/app/superagi/jobs/agent_executor.py", line 153, in execute_next_action
superagi-celery-1           |     response = spawned_agent.execute(agent_workflow_step)
superagi-celery-1           |   File "/app/superagi/agent/super_agi.py", line 162, in execute
superagi-celery-1           |     if response['content'] is None:
```

**Comment by brunobuger** [comment]
@AgimaFR, make sure:
1. Your Billing is set with subscription payment [https://platform.openai.com/account/billing/payment-methods](https://platform.openai.com/account/billing/payment-methods).
2. API Key is correct and inside the `config.yaml` file (OPENAI_API_KEY: <KEY>). 
3. If you changed your API KEY, try to re-load the stack. Running `docker-compose down` then `docker-compose up --build` again.

The error should disappear.

**Comment by AgimaFR** [comment]
@brunobuger Thanks for your quick reply 🙏
As mentioned, I did a full install of version 0.05 this morning after deleting everything.
My billing account is ok with OpenAI and I created a new API key specifically for the new installation.
I've just tried your tip `docker-compose down` then `docker-compose up --build` but the problem remains the same 😢

**Comment by brunobuger** [comment]
Hmmm
Then, you can try to do a full cleanup:
1. From SuperAGI folder, run`docker-compose down`
2. also, `docker volume prune -f`
3. Now access https://www.pinecone.io/, and delete the existent index.
4. Finally, `docker-compose up --build`

**Comment by AgimaFR** [comment]
Still the same problem after following your last instructions 😢 but thank you very much for your help.
```
superagi-celery-1           | [2023-06-16 14:22:04,076: INFO/ForkPoolWorker-7] error_code=invalid_api_key error_message= error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
superagi-celery-1           | [2023-06-16 14:22:04,077: WARNING/ForkPoolWorker-7] Exception:
superagi-celery-1           | [2023-06-16 14:22:04,077: WARNING/ForkPoolWorker-7]  
superagi-celery-1           | [2023-06-16 14:22:04,077: WARNING/ForkPoolWorker-7] <empty message>
superagi-celery-1           | [2023-06-16 14:22:04,115: INFO/MainProcess] Task execute_agent[06899716-6ad0-446e-a27e-9beaaa74321d] received
superagi-celery-1           | [2023-06-16 14:22:04,118: INFO/ForkPoolWorker-7] Task execute_agent[06899716-6ad0-446e-a27e-9beaaa74321d] retry: Retry in 25s: KeyError('content')
```
If you take a look at my OpenAI API key created for the new installation, you'll see that it's never been used before.
![API keys - OpenAI API 2023-06-16 16-28-22](https://github.com/TransformerOptimus/SuperAGI/assets/54644593/aa6e5954-dbe1-4454-a541-87a50752f21e)

**Comment by AgimaFR** [comment]
I found a solution:

- I simply clicked on the gear in the top right-hand corner,
- I entered my OPENAI API key
- I validated

Everything's ok now, although I still don't understand why it didn't work before 🤔

**Comment by Agnosaru** [comment]
Thanks, I had the same issue and this helped me resolve it.

**Comment by AgimaFR** [comment]
If you've had the same problem, there's definitely a problem in the code with reading the OPENAI API key 🤔

**Comment by DMTarmey** [comment]
I have also had same issue but iv also had error from openai which is error 404 which it says its not working because it not set as organisation, i when in to setting and changed account from personal to business and tried gain, no change.
