### ISSUE TITLE
Exited with code 2

### ISSUE THREAD

**Issue by nullvoid413** [TransformerOptimus/SuperAGI#405]
Hello.

So, I tried to build it for the first time and got to the "Initializing SuperAGI..." screen on localhost:3000, after I checked the console I got that Celery exited with code 2.

Here's te Docker logs:

> 2023-06-16 20:21:28 Usage: celery [OPTIONS] COMMAND [ARGS]...
2023-06-16 20:21:28 Try 'celery --help' for help.
2023-06-16 20:21:28 
2023-06-16 20:21:28 Error: Invalid value for '-A' / '--app': 
2023-06-16 20:21:28 Unable to load celery application.
2023-06-16 20:21:28 While trying to load the module superagi.worker the following error occurred:
2023-06-16 20:21:28 Traceback (most recent call last):
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 384, in find_app
2023-06-16 20:21:28     sym = symbol_by_name(app, imp=imp)
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
2023-06-16 20:21:28     return getattr(module, cls_name) if cls_name else module
2023-06-16 20:21:28 AttributeError: module 'superagi' has no attribute 'worker'
2023-06-16 20:21:28 
2023-06-16 20:21:28 During handling of the above exception, another exception occurred:
2023-06-16 20:21:28 
2023-06-16 20:21:28 Traceback (most recent call last):
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/celery/bin/celery.py", line 57, in convert
2023-06-16 20:21:28     return find_app(value)
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 387, in find_app
2023-06-16 20:21:28     sym = imp(app)
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/celery/utils/imports.py", line 105, in import_from_cwd
2023-06-16 20:21:28     return imp(module, package=package)
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2023-06-16 20:21:28     return _bootstrap._gcd_import(name[level:], package, level)
2023-06-16 20:21:28   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2023-06-16 20:21:28   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2023-06-16 20:21:28   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2023-06-16 20:21:28   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2023-06-16 20:21:28   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2023-06-16 20:21:28   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2023-06-16 20:21:28   File "/app/superagi/worker.py", line 5, in <module>
2023-06-16 20:21:28     from superagi.config.config import get_config
2023-06-16 20:21:28   File "/app/superagi/config/config.py", line 56, in <module>
2023-06-16 20:21:28     _config_instance = Config(ROOT_DIR + "/" + CONFIG_FILE)
2023-06-16 20:21:28   File "/app/superagi/config/config.py", line 48, in __init__
2023-06-16 20:21:28     config_data = self.load_config(config_file)
2023-06-16 20:21:28   File "/app/superagi/config/config.py", line 19, in load_config
2023-06-16 20:21:28     config_data = yaml.safe_load(file)
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
2023-06-16 20:21:28     return load(stream, SafeLoader)
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
2023-06-16 20:21:28     return loader.get_single_data()
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
2023-06-16 20:21:28     node = self.get_single_node()
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
2023-06-16 20:21:28     document = self.compose_document()
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
2023-06-16 20:21:28     node = self.compose_node(None, None)
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
2023-06-16 20:21:28     node = self.compose_mapping_node(anchor)
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 133, in compose_mapping_node
2023-06-16 20:21:28     item_value = self.compose_node(node, item_key)
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 64, in compose_node
2023-06-16 20:21:28     if self.check_event(AliasEvent):
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
2023-06-16 20:21:28     self.current_event = self.state()
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
2023-06-16 20:21:28     if not self.check_token(KeyToken, ValueToken, BlockEndToken):
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 116, in check_token
2023-06-16 20:21:28     self.fetch_more_tokens()
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 227, in fetch_more_tokens
2023-06-16 20:21:28     return self.fetch_alias()
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 610, in fetch_alias
2023-06-16 20:21:28     self.tokens.append(self.scan_anchor(AliasToken))
2023-06-16 20:21:28   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 929, in scan_anchor
2023-06-16 20:21:28     raise ScannerError("while scanning an %s" % name, start_mark,
2023-06-16 20:21:28 yaml.scanner.ScannerError: while scanning an alias
2023-06-16 20:21:28   in "/app/config.yaml", line 64, column 17
2023-06-16 20:21:28 expected alphabetic or numeric character, but found '='
2023-06-16 20:21:28   in "/app/config.yaml", line 64, column 20
2023-06-16 20:21:28 
2023-06-16 20:24:53 Usage: celery [OPTIONS] COMMAND [ARGS]...
2023-06-16 20:24:53 Try 'celery --help' for help.
2023-06-16 20:24:53 
2023-06-16 20:24:53 Error: Invalid value for '-A' / '--app': 
2023-06-16 20:24:53 Unable to load celery application.
2023-06-16 20:24:53 While trying to load the module superagi.worker the following error occurred:
2023-06-16 20:24:53 Traceback (most recent call last):
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 384, in find_app
2023-06-16 20:24:53     sym = symbol_by_name(app, imp=imp)
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
2023-06-16 20:24:53     return getattr(module, cls_name) if cls_name else module
2023-06-16 20:24:53 AttributeError: module 'superagi' has no attribute 'worker'
2023-06-16 20:24:53 
2023-06-16 20:24:53 During handling of the above exception, another exception occurred:
2023-06-16 20:24:53 
2023-06-16 20:24:53 Traceback (most recent call last):
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/celery/bin/celery.py", line 57, in convert
2023-06-16 20:24:53     return find_app(value)
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 387, in find_app
2023-06-16 20:24:53     sym = imp(app)
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/celery/utils/imports.py", line 105, in import_from_cwd
2023-06-16 20:24:53     return imp(module, package=package)
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2023-06-16 20:24:53     return _bootstrap._gcd_import(name[level:], package, level)
2023-06-16 20:24:53   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2023-06-16 20:24:53   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2023-06-16 20:24:53   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2023-06-16 20:24:53   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2023-06-16 20:24:53   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2023-06-16 20:24:53   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2023-06-16 20:24:53   File "/app/superagi/worker.py", line 5, in <module>
2023-06-16 20:24:53     from superagi.config.config import get_config
2023-06-16 20:24:53   File "/app/superagi/config/config.py", line 56, in <module>
2023-06-16 20:24:53     _config_instance = Config(ROOT_DIR + "/" + CONFIG_FILE)
2023-06-16 20:24:53   File "/app/superagi/config/config.py", line 48, in __init__
2023-06-16 20:24:53     config_data = self.load_config(config_file)
2023-06-16 20:24:53   File "/app/superagi/config/config.py", line 19, in load_config
2023-06-16 20:24:53     config_data = yaml.safe_load(file)
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
2023-06-16 20:24:53     return load(stream, SafeLoader)
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
2023-06-16 20:24:53     return loader.get_single_data()
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
2023-06-16 20:24:53     node = self.get_single_node()
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
2023-06-16 20:24:53     document = self.compose_document()
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
2023-06-16 20:24:53     node = self.compose_node(None, None)
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
2023-06-16 20:24:53     node = self.compose_mapping_node(anchor)
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 133, in compose_mapping_node
2023-06-16 20:24:53     item_value = self.compose_node(node, item_key)
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 64, in compose_node
2023-06-16 20:24:53     if self.check_event(AliasEvent):
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
2023-06-16 20:24:53     self.current_event = self.state()
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
2023-06-16 20:24:53     if not self.check_token(KeyToken, ValueToken, BlockEndToken):
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 116, in check_token
2023-06-16 20:24:53     self.fetch_more_tokens()
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 227, in fetch_more_tokens
2023-06-16 20:24:53     return self.fetch_alias()
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 610, in fetch_alias
2023-06-16 20:24:53     self.tokens.append(self.scan_anchor(AliasToken))
2023-06-16 20:24:53   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 929, in scan_anchor
2023-06-16 2
0:24:53     raise ScannerError("while scanning an %s" % name, start_mark,
2023-06-16 20:24:53 yaml.scanner.ScannerError: while scanning an alias
2023-06-16 20:24:53   in "/app/config.yaml", line 64, column 17
2023-06-16 20:24:53 expected alphabetic or numeric character, but found '='
2023-06-16 20:24:53   in "/app/config.yaml", line 64, column 20
2023-06-16 20:24:53 

<img width="861" alt="image" src="https://github.com/TransformerOptimus/SuperAGI/assets/18699811/ed7c47b5-93a7-4907-abf3-fa5c14fc80ff">
<img width="893" alt="image2" src="https://github.com/TransformerOptimus/SuperAGI/assets/18699811/efdcef9c-30e0-4673-b71c-2f5409ab13a3">

**Comment by nullvoid413** [comment]
Closed. Issue was on config file, line 64.
Everything’s is up and running now.
