### ISSUE TITLE
SUPERAGI not initializing???

### ISSUE THREAD

**Issue by JuLzSuN** [TransformerOptimus/SuperAGI#416]
I have followed installation instructions to a t but still now working. Page is stuck on initialising. Please help.

Here is log from terminal:

[+] Building 3.2s (37/37) FINISHED
 => [celery internal] load .dockerignore                                                                           0.0s
 => => transferring context: 50B                                                                                   0.0s
 => [celery internal] load build definition from DockerfileCelery                                                  0.0s
 => => transferring dockerfile: 419B                                                                               0.0s
 => [gui internal] load build definition from Dockerfile                                                           0.0s
 => => transferring dockerfile: 140B                                                                               0.0s
 => [gui internal] load .dockerignore                                                                              0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [celery internal] load metadata for docker.io/library/python:3.9                                               2.8s
 => [gui internal] load metadata for docker.io/library/node:lts                                                    2.1s
 => [backend internal] load .dockerignore                                                                          0.0s
 => => transferring context: 50B                                                                                   0.0s
 => [backend internal] load build definition from Dockerfile                                                       0.0s
 => => transferring dockerfile: 535B                                                                               0.0s
 => [celery auth] library/python:pull token for registry-1.docker.io                                               0.0s
 => [gui auth] library/node:pull token for registry-1.docker.io                                                    0.0s
 => [gui 1/5] FROM docker.io/library/node:lts@sha256:4a55308cc855cba1a925d19ae4e45838741dad2fd7bb8949a93b2a0f2ae3  0.0s
 => [gui internal] load build context                                                                              0.0s
 => => transferring context: 5.57kB                                                                                0.0s
 => CACHED [gui 2/5] WORKDIR /app                                                                                  0.0s
 => CACHED [gui 3/5] COPY package*.json ./                                                                         0.0s
 => CACHED [gui 4/5] RUN npm install                                                                               0.0s
 => CACHED [gui 5/5] COPY . .                                                                                      0.0s
 => [gui] exporting to image                                                                                       0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:e9a9bf2fd85918b24954b9bda41810f6d72145c94e6f0ec15366fe097df0328d                       0.0s
 => => naming to docker.io/library/superagi-main-gui                                                               0.0s
 => [backend internal] load build context                                                                          0.1s
 => => transferring context: 264.65kB                                                                              0.1s
 => [celery 1/8] FROM docker.io/library/python:3.9@sha256:98f018a1afd67f2e17a4abd5bfe09b998734ba7c1ee54780e7ed216  0.0s
 => [celery internal] load build context                                                                           0.1s
 => => transferring context: 264.65kB                                                                              0.1s
 => CACHED [backend 2/8] WORKDIR /app                                                                              0.0s
 => CACHED [celery 3/8] RUN pip install --upgrade pip                                                              0.0s
 => CACHED [celery 4/8] COPY requirements.txt .                                                                    0.0s
 => CACHED [celery 5/8] RUN pip install --no-cache-dir -r requirements.txt                                         0.0s
 => CACHED [celery 6/8] WORKDIR /app                                                                               0.0s
 => CACHED [celery 7/8] COPY . .                                                                                   0.0s
 => CACHED [celery 8/8] COPY config.yaml .                                                                         0.0s
 => [celery] exporting to image                                                                                    0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:967433d03064c0e1c2149602abaabd6594171677cc8f916a41d4f9ec4fe72524                       0.0s
 => => naming to docker.io/library/superagi-main-celery                                                            0.0s
 => CACHED [backend  3/10] COPY requirements.txt .                                                                 0.0s
 => CACHED [backend  4/10] RUN pip install --upgrade pip                                                           0.0s
 => CACHED [backend  5/10] RUN pip install --no-cache-dir -r requirements.txt                                      0.0s
 => CACHED [backend  6/10] COPY . .                                                                                0.0s
 => CACHED [backend  7/10] COPY config.yaml ./config.yaml                                                          0.0s
 => CACHED [backend  8/10] COPY entrypoint.sh /entrypoint.sh                                                       0.0s
 => CACHED [backend  9/10] COPY wait-for-it.sh /wait-for-it.sh                                                     0.0s
 => CACHED [backend 10/10] RUN chmod +x /entrypoint.sh /wait-for-it.sh                                             0.0s
 => [backend] exporting to image                                                                                   0.1s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:cf5b122c74ca662f54dddf88ede25b8c68080c954172f21361a45acb252c7019                       0.0s
 => => naming to docker.io/library/superagi-main-backend                                                           0.0s
[+] Running 7/7
 ✔ Network superagi-main_super_network            Created                                                          0.0s
 ✔ Volume "superagi-main_superagi_postgres_data"  Created                                                          0.0s
 ✔ Container superagi-main-super__postgres-1      Created                                                          0.5s
 ✔ Container superagi-main-gui-1                  Created                                                         62.2s
 ✔ Container superagi-main-super__redis-1         Created                                                          0.5s
 ✔ Container superagi-main-celery-1               Created                                                         60.1s
 ✔ Container superagi-main-backend-1              Created                                                         60.1s
Attaching to superagi-main-backend-1, superagi-main-celery-1, superagi-main-gui-1, superagi-main-super__postgres-1, superagi-main-super__redis-1
superagi-main-super__postgres-1  | The files belonging to this database system will be owned by user "postgres".
superagi-main-super__postgres-1  | This user must also own the server process.
superagi-main-super__postgres-1  |
superagi-main-super__postgres-1  | The database cluster will be initialized with locale "en_US.utf8".
superagi-main-super__postgres-1  | The default database encoding has accordingly been set to "UTF8".
superagi-main-super__postgres-1  | The default text search configuration will be set to "english".
superagi-main-super__postgres-1  |
superagi-main-super__postgres-1  | Data page checksums are disabled.
superagi-main-super__postgres-1  |
superagi-main-super__postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
superagi-main-super__postgres-1  | creating subdirectories ... ok
superagi-main-super__postgres-1  | selecting dynamic shared memory implementation ... posix
superagi-main-super__postgres-1  | selecting default max_connections ... 100
superagi-main-super__postgres-1  | selecting default shared_buffers ... 128MB
superagi-main-super__postgres-1  | selecting default time zone ... Etc/UTC
superagi-main-super__postgres-1  | creating configuration files ... ok
superagi-main-super__postgres-1  | running bootstrap script ... ok
superagi-main-super__redis-1     | 1:C 19 Jun 2023 09:19:42.452 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
superagi-main-super__redis-1     | 1:C 19 Jun 2023 09:19:42.453 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
superagi-main-super__redis-1     | 1:C 19 Jun 2023 09:19:42.453 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
superagi-main-super__redis-1     | 1:M 19 Jun 2023 09:19:42.454 * monotonic clock: POSIX clock_gettime
superagi-main-super__redis-1     | 1:M 19 Jun 2023 09:19:42.456 * Running mode=standalone, port=6379.
superagi-main-super__redis-1     | 1:M 19 Jun 2023 09:19:42.457 # Server initialized
superagi-main-super__redis-1     | 1:M 19 Jun 2023 09:19:42.457 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
superagi-main-super__redis-1     | 1:M 19 Jun 2023 09:19:42.457 * Ready to accept connections
superagi-main-gui-1              |
superagi-main-gui-1              | > super-agi@0.1.0 dev
superagi-main-gui-1              | > next dev
superagi-main-gui-1              |
superagi-main-super__postgres-1  | performing post-bootstrap initialization ... ok
superagi-main-gui-1              | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
superagi-main-celery-1           | Usage: celery [OPTIONS] COMMAND [ARGS]...
superagi-main-celery-1           | Try 'celery --help' for help.
superagi-main-celery-1           |
superagi-main-celery-1           | Error: Invalid value for '-A' / '--app':
superagi-main-celery-1           | Unable to load celery application.
superagi-main-celery-1           | While trying to load the module superagi.worker the following error occurred:
superagi-main-celery-1           | Traceback (most recent call last):
superagi-main-celery-1           |   File "/usr/local/lib/python3.9/site-packages/celery/bin/celery.py", line 57, in convert
superagi-main-celery-1           |     return find_app(value)
superagi-main-celery-1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 384, in find_app
superagi-main-celery-1           |     sym = symbol_by_name(app, imp=imp)
superagi-main-celery-1           |   File "/usr/local/lib/python3.9/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
superagi-main-celery-1           |     module = imp(module_name, package=package, **kwargs)
superagi-main-celery-1           |   File "/usr/local/lib/python3.9/site-packages/celery/utils/imports.py", line 105, in import_from_cwd
superagi-main-celery-1           |     return imp(module, package=package)
superagi-main-celery-1           |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
superagi-main-celery-1           |     return _bootstrap._gcd_import(name[level:], package, level)
superagi-main-celery-1           |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
superagi-main-celery-1           |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
superagi-main-celery-1           |   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
superagi-main-celery-1           | ModuleNotFoundError: No module named 'superagi'
superagi-main-celery-1           |
superagi-main-gui-1              | Attention: Next.js now collects completely anonymous telemetry regarding usage.
superagi-main-gui-1              | This information is used to shape Next.js' roadmap and prioritize features.
superagi-main-gui-1              | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
superagi-main-gui-1              | https://nextjs.org/telemetry
superagi-main-gui-1              |
superagi-main-backend-1          | wait-for-it.sh: waiting 60 seconds for super__postgres:5432
superagi-main-gui-1              | - event compiled client and server successfully in 20s (1314 modules)
superagi-main-celery-1 exited with code 2
superagi-main-gui-1              | - wait compiling...
superagi-main-super__postgres-1  | syncing data to disk ... ok
superagi-main-super__postgres-1  |
superagi-main-super__postgres-1  |
superagi-main-super__postgres-1  | Success. You can now start the database server using:
superagi-main-super__postgres-1  |
superagi-main-super__postgres-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
superagi-main-super__postgres-1  |
superagi-main-super__postgres-1  | initdb: warning: enabling "trust" authentication for local connections
superagi-main-super__postgres-1  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
superagi-main-gui-1              | - event compiled client and server successfully in 928 ms (1314 modules)
superagi-main-super__postgres-1  | waiting for server to start....2023-06-19 09:20:14.203 UTC [48] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.207 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.215 UTC [51] LOG:  database system was shut down at 2023-06-19 09:19:43 UTC
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.223 UTC [48] LOG:  database system is ready to accept connections
superagi-main-super__postgres-1  |  done
superagi-main-super__postgres-1  | server started
superagi-main-super__postgres-1  | CREATE DATABASE
superagi-main-super__postgres-1  |
superagi-main-super__postgres-1  |
superagi-main-super__postgres-1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
superagi-main-super__postgres-1  |
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.464 UTC [48] LOG:  received fast shutdown request
superagi-main-super__postgres-1  | waiting for server to shut down....2023-06-19 09:20:14.471 UTC [48] LOG:  aborting any active transactions
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.473 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.473 UTC [49] LOG:  shutting down
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.477 UTC [49] LOG:  checkpoint starting: shutdown immediate
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.610 UTC [49] LOG:  checkpoint complete: wrote 918 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.026 s, sync=0.097 s, total=0.137 s; sync files=250, longest=0.015 s, average=0.001 s; distance=4223 kB, estimate=4223 kB
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.616 UTC [48] LOG:  database system is shut down
superagi-main-super__postgres-1  |  done
superagi-main-super__postgres-1  | server stopped
superagi-main-super__postgres-1  |
superagi-main-super__postgres-1  | PostgreSQL init process complete; ready for start up.
superagi-main-super__postgres-1  |
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.698 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.698 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.698 UTC [1] LOG:  listening on IPv6 address "::", port 5432
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.704 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.712 UTC [64] LOG:  database system was shut down at 2023-06-19 09:20:14 UTC
superagi-main-super__postgres-1  | 2023-06-19 09:20:14.719 UTC [1] LOG:  database system is ready to accept connections
superagi-main-backend-1          | wait-for-it.sh: super__postgres:5432 is available after 27 seconds
superagi-main-backend-1          | Traceback (most recent call last):
superagi-main-backend-1          |   File "/usr/local/bin/alembic", line 8, in <module>
superagi-main-backend-1          |     sys.exit(main())
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line 632, in main
superagi-main-backend-1          |     CommandLine(prog=prog).main(argv=argv)
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line 626, in main
superagi-main-backend-1          |     self.run_cmd(cfg, options)
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line 603, in run_cmd
superagi-main-backend-1          |     fn(
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 385, in upgrade
superagi-main-backend-1          |     script.run_env()
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 582, in run_env
superagi-main-backend-1          |     util.load_python_file(self.dir, "env.py")
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
superagi-main-backend-1          |     module = load_module_py(module_id, path)
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
superagi-main-backend-1          |     spec.loader.exec_module(module)  # type: ignore
superagi-main-backend-1          |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
superagi-main-backend-1          |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
superagi-main-backend-1          |   File "migrations/env.py", line 8, in <module>
superagi-main-backend-1          |     from superagi.config.config import get_config
superagi-main-backend-1          | ModuleNotFoundError: No module named 'superagi'
superagi-main-backend-1          | INFO:     Will watch for changes in these directories: ['/app']
superagi-main-backend-1          | INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
superagi-main-backend-1          | INFO:     Started reloader process [1] using WatchFiles
superagi-main-backend-1          | Process SpawnProcess-1:
superagi-main-backend-1          | Traceback (most recent call last):
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
superagi-main-backend-1          |     self.run()
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
superagi-main-backend-1          |     self._target(*self._args, **self._kwargs)
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
superagi-main-backend-1          |     target(sockets=sockets)
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
superagi-main-backend-1          |     return asyncio.run(self.serve(sockets=sockets))
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
superagi-main-backend-1          |     return loop.run_until_complete(main)
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
superagi-main-backend-1          |     return future.result()
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
superagi-main-backend-1          |     config.load()
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 473, in load
superagi-main-backend-1          |     self.loaded_app = import_from_string(self.app)
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 24, in import_from_string
superagi-main-backend-1          |     raise exc from None
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
superagi-main-backend-1          |     module = importlib.import_module(module_str)
superagi-main-backend-1          |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
superagi-main-backend-1          |     return _bootstrap._gcd_import(name[level:], package, level)
superagi-main-backend-1          |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
superagi-main-backend-1          |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
superagi-main-backend-1          |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
superagi-main-backend-1          |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
superagi-main-backend-1          |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
superagi-main-backend-1          |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
superagi-main-backend-1          |   File "/app/main.py", line 17, in <module>
superagi-main-backend-1          |     import superagi
superagi-main-backend-1          | ModuleNotFoundError: No module named 'superagi'
superagi-main-gui-1              | - wait compiling /_error (client and server)...
superagi-main-gui-1              | - event compiled client and server successfully in 383 ms (1315 modules)
superagi-main-gui-1              | Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap"). Use Document instead.
superagi-main-gui-1              | See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component
superagi-main-gui-1              | Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"). Use Document instead.
superagi-main-gui-1              | See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component
superagi-main-gui-1              | - wait compiling /favicon.ico/route (client and server)...
superagi-main-gui-1              | - event compiled successfully in 633 ms (146 modules)
superagi-main-super__postgres-1  | 2023-06-19 09:25:14.810 UTC [62] LOG:  checkpoint starting: time
superagi-main-super__postgres-1  | 2023-06-19 09:25:18.965 UTC [62] LOG:  checkpoint complete: wrote 44 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.122 s, sync=0.017 s, total=4.155 s; sync files=12, longest=0.011 s, average=0.002 s; distance=252 kB, estimate=252 kB

**Comment by JuLzSuN** [comment]
this was fixed by deleting the SuperAGi-main file and starting agin but only having one config.yaml file. If the file is recognised by any software you do not have to write .yaml or it will give you error
