### ISSUE TITLE
getting the module not found error

### ISSUE THREAD

**Issue by gsutton57** [TransformerOptimus/SuperAGI#506]
When running on localhost:3000 it just shows it is initializing.  Here is where I think the problem is but don't know if that is the problem or how to fix it?
superagi-celery-1           |     return _bootstrap._gcd_import(name[level:], package, level)        
superagi-celery-1           |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import      
superagi-celery-1           |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load   
superagi-celery-1           |   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
superagi-celery-1           | ModuleNotFoundError: No module named 'superagi'
superagi-celery-1           |

**Comment by neelayan7** [comment]
Are you running from the Root folder?
If yes, please send some more detailed logs.

**Comment by gsutton57** [comment]
I think that may be the problem Here is where I am running from \Users\George\OneDrive\Desktop\SuperAGI

**Comment by gsutton57** [comment]
sorry C:\Users\George\OneDrive\Desktop\SuperAGI

**Comment by gsutton57** [comment]
PS C:\Users\George\OneDrive\Desktop\SuperAGI> docker-compose up --build
[+] Building 3.7s (37/37) FINISHED
 => [backend internal] load .dockerignore                                       0.1s
 => => transferring context: 51B                                                0.0s 
 => [backend internal] load build definition from Dockerfile                    0.1s 
 => => transferring dockerfile: 556B                                            0.0s
 => [celery internal] load metadata for docker.io/library/python:3.9            0.9s 
 => [backend auth] library/python:pull token for registry-1.docker.io           0.0s
 => [celery 1/8] FROM docker.io/library/python:3.9@sha256:98f018a1afd67f2e17a4  0.0s
 => [backend internal] load build context                                       0.1s 
 => => transferring context: 19.88kB                                            0.0s 
 => CACHED [celery 2/8] WORKDIR /app                                            0.0s 
 => CACHED [backend  3/10] COPY requirements.txt .                              0.0s
 => CACHED [backend  4/10] RUN pip install --upgrade pip                        0.0s 
 => CACHED [backend  5/10] RUN pip install --no-cache-dir -r requirements.txt   0.0s 
 => CACHED [backend  6/10] COPY . .                                             0.0s 
 => CACHED [backend  7/10] COPY config.yaml ./config.yaml                       0.0s 
 => CACHED [backend  8/10] COPY entrypoint.sh ./entrypoint.sh                   0.0s 
 => CACHED [backend  9/10] COPY wait-for-it.sh ./wait-for-it.sh                 0.0s 
 => CACHED [backend 10/10] RUN chmod +x ./entrypoint.sh ./wait-for-it.sh        0.0s 
 => [backend] exporting to image                                                0.0s 
 => => exporting layers                                                         0.0s 
 => => writing image sha256:059635746413a425bc444f97ce2c74c8e37b70253d16900d17  0.0s 
 => => naming to docker.io/library/superagi-backend                             0.0s 
 => [celery internal] load .dockerignore                                        0.0s 
 => => transferring context: 51B                                                0.0s 
 => [celery internal] load build definition from DockerfileCelery               0.1s 
 => => transferring dockerfile: 434B                                            0.0s 
 => [gui internal] load build definition from Dockerfile                        0.0s 
 => => transferring dockerfile: 149B                                            0.0s 
 => [gui internal] load .dockerignore                                           0.0s 
 => => transferring context: 2B                                                 0.0s 
 => [gui internal] load metadata for docker.io/library/node:lts                 0.6s 
 => [celery internal] load build context                                        0.1s 
 => => transferring context: 19.13kB                                            0.0s 
 => CACHED [celery 3/8] RUN pip install --upgrade pip                           0.0s 
 => CACHED [celery 4/8] COPY requirements.txt .                                 0.0s 
 => CACHED [celery 5/8] RUN pip install --no-cache-dir -r requirements.txt      0.0s 
 => CACHED [celery 6/8] WORKDIR /app                                            0.0s 
 => CACHED [celery 7/8] COPY . .                                                0.0s 
 => CACHED [celery 8/8] COPY config.yaml .                                      0.0s 
 => [celery] exporting to image                                                 0.0s 
 => => exporting layers                                                         0.0s 
 => => writing image sha256:b4ed22cf28a86e6655cdd779c0ba82bdecb3c949f39c6cec3d  0.0s 
 => => naming to docker.io/library/superagi-celery                              0.0s 
 => [gui auth] library/node:pull token for registry-1.docker.io                 0.0s 
 => [gui 1/5] FROM docker.io/library/node:lts@sha256:19892542dd80e33aec50a5161  0.0s 
 => [gui internal] load build context                                           0.0s 
 => => transferring context: 6.08kB                                             0.0s 
 => CACHED [gui 2/5] WORKDIR /app                                               0.0s 
 => CACHED [gui 3/5] COPY package*.json ./                                      0.0s 
 => CACHED [gui 4/5] RUN npm install                                            0.0s 
 => CACHED [gui 5/5] COPY . .                                                   0.0s 
 => [gui] exporting to image                                                    0.0s 
 => => exporting layers                                                         0.0s 
 => => writing image sha256:2604750301cc6dc768484f4c94fc0b7ff9bb1ce43baa39941b  0.0s 
 => => naming to docker.io/library/superagi-gui                                 0.0s 
[+] Running 6/0
 ✔ Container superagi-super__redis-1     Running                                0.0s 
 ✔ Container superagi-gui-1              Running                                0.0s 
 ✔ Container superagi-super__postgres-1  Running                                0.0s 
 ✔ Container superagi-backend-1          Runn...                                0.0s 
 ✔ Container superagi-celery-1           Creat...                               0.0s 
 ✔ Container superagi-proxy-1            Runnin...                              0.0s 
Attaching to superagi-backend-1, superagi-celery-1, superagi-gui-1, superagi-proxy-1, superagi-super__postgres-1, superagi-super__redis-1
superagi-celery-1           | Usage: celery [OPTIONS] COMMAND [ARGS]...
superagi-celery-1           | Try 'celery --help' for help.
superagi-celery-1           |
superagi-celery-1           | Error: Invalid value for '-A' / '--app':
superagi-celery-1           | Unable to load celery application.
superagi-celery-1           | While trying to load the module superagi.worker the following error occurred:
superagi-celery-1           | Traceback (most recent call last):
superagi-celery-1           |   File "/usr/local/lib/python3.9/site-packages/celery/bin/celery.py", line 57, in convert
superagi-celery-1           |     return find_app(value)
superagi-celery-1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 384, in find_app
superagi-celery-1           |     sym = symbol_by_name(app, imp=imp)
superagi-celery-1           |   File "/usr/local/lib/python3.9/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
superagi-celery-1           |     module = imp(module_name, package=package, **kwargs)
superagi-celery-1           |   File "/usr/local/lib/python3.9/site-packages/celery/utils/imports.py", line 105, in import_from_cwd
superagi-celery-1           |     return imp(module, package=package)
superagi-celery-1           |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
superagi-celery-1           |     return _bootstrap._gcd_import(name[level:], package, level)
superagi-celery-1           |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
superagi-celery-1           |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
superagi-celery-1           |   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
superagi-celery-1           | ModuleNotFoundError: No module named 'superagi'        
superagi-celery-1           |

**Comment by gsutton57** [comment]
Now it is giving this error 
request returned Internal Server Error for API route and version http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.42/containers/8a2134ee6db5c68706f520a6a73d2fa788b990d5a74525bd3fb5ee5dc31c13b8/json, check if the server supports the requested API version
PS C:\Users\George\OneDrive\Desktop\SuperAGI>

**Comment by gsutton57** [comment]
Here is the docker log 
2023-06-27 12:47:33 superagi-celery-1           | ModuleNotFoundError: No module named 'superagi'
2023-06-27 12:47:33 superagi-celery-1           | 
1969-12-31 19:00:00 superagi-celery-1 exited with code 2
1969-12-31 19:00:00 superagi-proxy-1            | 2023-06-27T16:47:36.185281653Z 172.18.0.1 - - [27/Jun/2023:16:47:36 +0000] "GET /_next/webpack-hmr HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
2023-06-27 12:47:45 superagi-proxy-1            | 172.18.0.1 - - [27/Jun/20

**Comment by gsutton57** [comment]
I am really sorry to be ignorant and don't want to waste your time, if you can just suggest some links that I can go to study and get a better understanding, I would really appreciate it.

**Comment by gsutton57** [comment]
Yeah so I am pretty sure this is where my problem is.
File "/app/main.py", line 17, in <module>
superagi-backend-1          |     import superagi
superagi-backend-1          | ModuleNotFoundError: No module named 'superagi'
