### ISSUE TITLE
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "super__postgres" to address: Unknown host

### ISSUE THREAD

**Issue by turb1te** [TransformerOptimus/SuperAGI#712]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Windows

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I ran 'run.bat' after configuring 'config.yaml'. It shows me the error from the logs.

### Upload Error Log Content

(venv) C:\Users\turb1te\Downloads\SuperAGI-main>.\run.bat Checking if config.yaml file exists... Checking if virtual environment is activated... Virtual environment is already activated. Checking requirements... Installing requirements... Running test.py with python... 2023-07-10 10:15:08 FLE Daylight Time - Super AGI - ERROR - [C:\Users\turb1te\Downloads\SuperAGI-main\superagi\models\db.py:40] - Unable to connect to the database:(psycopg2.OperationalError) could not translate host name "super__postgres" to address: Unknown host  (Background on this error at: https://sqlalche.me/e/20/e3q8) Traceback (most recent call last):   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__     self._dbapi_connection = engine.raw_connection()                              ^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3288, in raw_connection     return self.pool.connect()            ^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 452, in connect     return _ConnectionFairy._checkout(self)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1267, in _checkout     fairy = _ConnectionRecord.checkout(pool)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout     rec = pool._do_get()           ^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 169, in _do_get     with util.safe_reraise():   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__     raise exc_value.with_traceback(exc_tb)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 167, in _do_get     return self._create_connection()            ^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 393, in _create_connection     return _ConnectionRecord(self)            ^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 678, in __init__     self.__connect()   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 902, in __connect     with util.safe_reraise():   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__     raise exc_value.with_traceback(exc_tb)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 898, in __connect     self.dbapi_connection = connection = pool._invoke_creator(self)                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 637, in connect     return dialect.connect(*cargs, **cparams)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 615, in connect     return self.loaded_dbapi.connect(*cargs, **cparams)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ psycopg2.OperationalError: could not translate host name "super__postgres" to address: Unknown host   The above exception was the direct cause of the following exception:  Traceback (most recent call last):   File "C:\Users\turb1te\Downloads\SuperAGI-main\test.py", line 109, in <module>     run_superagi_cli(agent_name=agent_name, agent_description=agent_description, agent_goals=agent_goals)   File "C:\Users\turb1te\Downloads\SuperAGI-main\test.py", line 45, in run_superagi_cli     session.flush()  # Flush pending changes to generate the agent's ID     ^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4142, in flush     self._flush(objects)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4277, in _flush     with util.safe_reraise():   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__     raise exc_value.with_traceback(exc_tb)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4238, in _flush     flush_context.execute()   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute     rec.execute(self)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute     util.preloaded.orm_persistence.save_obj(   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 60, in save_obj     for (   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 221, in _organize_states_for_save     for state, dict_, mapper, connection in _connections_for_states(   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1726, in _connections_for_states     connection = uowtransaction.transaction.connection(base_mapper)                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "<string>", line 2, in connection   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 136, in _go     ret_value = fn(self, *arg, **kw)                 ^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 966, in connection     return self._connection_for_bind(bind, execution_options)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "<string>", line 2, in _connection_for_bind   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 136, in _go     ret_value = fn(self, *arg, **kw)                 ^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1097, in _connection_for_bind     conn = self._parent._connection_for_bind(bind, execution_options)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "<string>", line 2, in _connection_for_bind   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 136, in _go     ret_value = fn(self, *arg, **kw)                 ^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1109, in _connection_for_bind     conn = bind.connect()            ^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3264, in connect     return self._connection_cls(self)            ^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__     Connection._handle_dbapi_exception_noconnection(   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2426, in _handle_dbapi_exception_noconnection     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__     self._dbapi_connection = engine.raw_connection()                              ^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3288, in raw_connection     return self.pool.connect()            ^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 452, in connect     return _ConnectionFairy._checkout(self)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1267, in _checkout     fairy = _ConnectionRecord.checkout(pool)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout     rec = pool._do_get()           ^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 169, in _do_get     with util.safe_reraise():   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__     raise exc_value.with_traceback(exc_tb)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 167, in _do_get     return self._create_connection()            ^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 393, in _create_connection     return _ConnectionRecord(self)            ^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 678, in __init__     self.__connect()   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 902, in __connect     with util.safe_reraise():   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__     raise exc_value.with_traceback(exc_tb)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 898, in __connect     self.dbapi_connection = connection = pool._invoke_creator(self)                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 637, in connect     return dialect.connect(*cargs, **cparams)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 615, in connect     return self.loaded_dbapi.connect(*cargs, **cparams)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "super__postgres" to address: Unknown host  (Background on this error at: https://sqlalche.me/e/20/e3q8) Running test.py with python3... 2023-07-10 10:15:14 FLE Daylight Time - Super AGI - ERROR - [C:\Users\turb1te\Downloads\SuperAGI-main\superagi\models\db.py:40] - Unable to connect to the database:(psycopg2.OperationalError) could not translate host name "super__postgres" to address: Unknown host  (Background on this error at: https://sqlalche.me/e/20/e3q8) Traceback (most recent call last):   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__     self._dbapi_connection = engine.raw_connection()                              ^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3288, in raw_connection     return self.pool.connect()            ^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 452, in connect     return _ConnectionFairy._checkout(self)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1267, in _checkout     fairy = _ConnectionRecord.checkout(pool)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout     rec = pool._do_get()           ^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 169, in _do_get     with util.safe_reraise():   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__     raise exc_value.with_traceback(exc_tb)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 167, in _do_get     return self._create_connection()            ^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 393, in _create_connection     return _ConnectionRecord(self)            ^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 678, in __init__     self.__connect()   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 902, in __connect     with util.safe_reraise():   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__     raise exc_value.with_traceback(exc_tb)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 898, in __connect     self.dbapi_connection = connection = pool._invoke_creator(self)                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 637, in connect     return dialect.connect(*cargs, **cparams)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 615, in connect     return self.loaded_dbapi.connect(*cargs, **cparams)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ psycopg2.OperationalError: could not translate host name "super__postgres" to address: Unknown host   The above exception was the direct cause of the following exception:  Traceback (most recent call last):   File "C:\Users\turb1te\Downloads\SuperAGI-main\test.py", line 109, in <module>     run_superagi_cli(agent_name=agent_name, agent_description=agent_description, agent_goals=agent_goals)   File "C:\Users\turb1te\Downloads\SuperAGI-main\test.py", line 45, in run_superagi_cli     session.flush()  # Flush pending changes to generate the agent's ID     ^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4142, in flush     self._flush(objects)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4277, in _flush     with util.safe_reraise():   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__     raise exc_value.with_traceback(exc_tb)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4238, in _flush     flush_context.execute()   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute     rec.execute(self)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute     util.preloaded.orm_persistence.save_obj(   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 60, in save_obj     for (   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 221, in _organize_states_for_save     for state, dict_, mapper, connection in _connections_for_states(   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1726, in _connections_for_states     connection = uowtransaction.transaction.connection(base_mapper)                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "<string>", line 2, in connection   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 136, in _go     ret_value = fn(self, *arg, **kw)                 ^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 966, in connection     return self._connection_for_bind(bind, execution_options)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "<string>", line 2, in _connection_for_bind   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 136, in _go     ret_value = fn(self, *arg, **kw)                 ^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1097, in _connection_for_bind     conn = self._parent._connection_for_bind(bind, execution_options)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "<string>", line 2, in _connection_for_bind   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 136, in _go     ret_value = fn(self, *arg, **kw)                 ^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1109, in _connection_for_bind     conn = bind.connect()            ^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3264, in connect     return self._connection_cls(self)            ^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__     Connection._handle_dbapi_exception_noconnection(   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2426, in _handle_dbapi_exception_noconnection     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__     self._dbapi_connection = engine.raw_connection()                              ^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3288, in raw_connection     return self.pool.connect()            ^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 452, in connect     return _ConnectionFairy._checkout(self)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1267, in _checkout     fairy = _ConnectionRecord.checkout(pool)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout     rec = pool._do_get()           ^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 169, in _do_get     with util.safe_reraise():   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__     raise exc_value.with_traceback(exc_tb)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 167, in _do_get     return self._create_connection()            ^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 393, in _create_connection     return _ConnectionRecord(self)            ^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 678, in __init__     self.__connect()   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 902, in __connect     with util.safe_reraise():   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__     raise exc_value.with_traceback(exc_tb)   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 898, in __connect     self.dbapi_connection = connection = pool._invoke_creator(self)                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 637, in connect     return dialect.connect(*cargs, **cparams)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 615, in connect     return self.loaded_dbapi.connect(*cargs, **cparams)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\turb1te\Downloads\SuperAGI-0.0.7\venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "super__postgres" to address: Unknown host  (Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by turb1te** [comment]
I forgot about Docker 😄 That was the reason.
