### ISSUE TITLE
UnboundLocalError: local variable 'tools_dir' referenced before assignment

### ISSUE THREAD

**Issue by LivingElevated** [TransformerOptimus/SuperAGI#957]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

MacOS

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5(16k)

### Which area covers your issue best?

Tools

### Describe your issue.

Error starting new agent after last update with tool build and imported from Github.

Was required to import this way because after the last update personal tools won't allow you to access them if they are in the tool folder

```
superagi-celery-1           | 2023-08-02 21:37:15 UTC - Super AGI - INFO - [/app/superagi/worker.py:48] - Execute agent:2023-08-02T21:36:18.647141,166
superagi-celery-1           | [2023-08-02 21:37:15,079: INFO/ForkPoolWorker-8] Execute agent:2023-08-02T21:36:18.647141,166
superagi-celery-1           | [2023-08-02 21:37:17,188: ERROR/ForkPoolWorker-8] Task execute_agent[6d5a4806-1987-417a-b11e-71c18ad99c04] raised unexpected: UnboundLocalError("local variable 'tools_dir' referenced before assignment")
superagi-celery-1           | Traceback (most recent call last):
superagi-celery-1           |   File "/opt/venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
superagi-celery-1           |     R = retval = fun(*args, **kwargs)
superagi-celery-1           |   File "/opt/venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
superagi-celery-1           |     return self.run(*args, **kwargs)
superagi-celery-1           |   File "/opt/venv/lib/python3.10/site-packages/celery/app/autoretry.py", line 54, in run
superagi-celery-1           |     ret = task.retry(exc=exc, **retry_kwargs)
superagi-celery-1           |   File "/opt/venv/lib/python3.10/site-packages/celery/app/task.py", line 717, in retry
superagi-celery-1           |     raise_with_context(exc)
superagi-celery-1           |   File "/opt/venv/lib/python3.10/site-packages/celery/app/autoretry.py", line 34, in run
superagi-celery-1           |     return task._orig_run(*args, **kwargs)
superagi-celery-1           |   File "/app/superagi/worker.py", line 49, in execute_agent
superagi-celery-1           |     AgentExecutor().execute_next_action(agent_execution_id=agent_execution_id)
superagi-celery-1           |   File "/app/superagi/jobs/agent_executor.py", line 228, in execute_next_action
superagi-celery-1           |     tool = AgentExecutor.create_object(tool, session)
superagi-celery-1           |   File "/app/superagi/jobs/agent_executor.py", line 93, in create_object
superagi-celery-1           |     parsed_tools_dir = tools_dir.rstrip("/")
superagi-celery-1           | UnboundLocalError: local variable 'tools_dir' referenced before assignment
```

### How to replicate your Issue?

Replicate by adding a toolkit from GitHub, and then try to start a new agent with the tools in the toolkit

### Upload Error Log Content

ERROR/ForkPoolWorker-8] Task execute_agent[6d5a4806-1987-417a-b11e-71c18ad99c04] raised unexpected: UnboundLocalError("local variable 'tools_dir' referenced before assignment")

**Comment by coder5492** [comment]
Appreciate you opening this issue. We'll work on replicating it and provide feedback accordingly. Thanks!
